### ISSUE TITLE
Look into using a voting widget for docs feedback

### ISSUE THREAD

**Issue by ptgott** [gravitational/docs#137]
This idea came from Ev. Some companies use voting widgets to identify the most confusing docs pages and prioritize fixes. We can consider doing this in our own docs.

**Comment by ptgott** [comment]
I like the unobtrusive approach to a "Rate this page" component in the Jira docs:

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/25250668/186485285-c263e3d7-0047-4c79-9c10-256e0c83470e.png">

**Comment by hatched** [comment]
I don't think a voting widget will ultimately get us towards the goal of "identifying the most confusing docs pages and prioritize fixes".

Something more targeted like a link that says "having trouble with these docs?" or "issues on this page?" which could direct the user to submit a more detailed response instead of getting the odd 2 star review on a page and then wondering what the real issue was.

**Comment by ptgott** [comment]
That makes sense—a voting widget would be more helpful if we had high enough docs traffic to, say, measure the impact of docs changes over time (i.e., with tight feedback loop between docs changes and score changes) or run A/B tests on certain changes.

At the same time, there are probably ways to get visibility into how confusing/clear docs pages are that require less effort from users than the "click Improve -> open an issue" workflow.

**Comment by ptgott** [comment]
Closing as not planned. We would need higher pageview volume to generate interesting data, and can already get feedback via the `Improve the Docs` button at the bottom of each page.
