### ISSUE TITLE
Allow docs images to pop up

### ISSUE THREAD

**Issue by ptgott** [gravitational/docs#158]
We need to include screenshots in the docs pretty regularly, yet the rendered size of these images is too small to make out details. Here's a screenshot taken of `goteleport.com/docs/desktop-access/getting-started` on Sep 26, 2022:

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/25250668/192385256-a10c671a-c7ba-452f-b4e7-43b3e2e3354b.png">

We should make it possible to expand images on click, i.e., through a modal. 

We could add another prop to the [`Image` or `Figure` components](https://github.com/gravitational/docs/blob/7822c26373eec730489d142296796a11de7e869e/components/MDX/Image.tsx) to make this configurable. By default, images would pop up, allowing authors to use the regular Markdown image syntax. This would mean that all screenshot images would include the popup behavior, and we would only need to disable this behavior for images where it wouldn't make sense.

**Comment by ninaTorgunakova** [comment]
I think we can disable this option automatically if the image's original width is less than the maximum width of its container (because there is no need to enlarge an image if it doesn't use the full width anyway). And we can add the new boolean prop into `Figure` (`noPopUp` for example) additionally in case there is a need to customize this option.

**Comment by ptgott** [comment]
@ninaTorgunakova Sounds good!
