### ISSUE TITLE
Focus docs UX on text

### ISSUE THREAD

**Issue by klizhentas** [gravitational/docs#93]
This is sparked by discussion and some tweaks here:

https://github.com/gravitational/docs/issues/85

I would like to make small changes to our documentation to read more like a book and focus reader's attention on text.

Here is the great example:

https://docs.djangoproject.com/en/4.0/intro/install/

From our docs team side, we can reduce reliance on big tiles (use them less frequently and with caution), but I would like to make some touch ups to other design elements too:

1. Make title read more like a classic title to remove banner-style

<img width="1652" alt="title-style" src="https://user-images.githubusercontent.com/13717/177821949-456ec2f4-83c1-4d0e-8dd8-c2099d576414.png">

2. Make video banner less intrusive, may be remove boundaries

3. Make tiles less intrusive, with less purple and read more like doc headers:

<img width="401" alt="Screen Shot 2022-07-07 at 9 17 51 AM" src="https://user-images.githubusercontent.com/13717/177822177-b01bba3c-c8ac-42b8-bea7-20c79d824c82.png">

4. Make tabs more lightweight, right now they are too heavy and try another theme for code that focuses on actual code.

<img width="952" alt="Screen Shot 2022-07-07 at 9 18 43 AM" src="https://user-images.githubusercontent.com/13717/177822295-b696ccfa-5ce9-4fa9-95e3-1151e15382a4.png">

5. Make notifications less disruptive to the readers flow, they take too much attention with very bright frames:

<img width="1004" alt="Screen Shot 2022-07-07 at 9 19 09 AM" src="https://user-images.githubusercontent.com/13717/177822431-73aa909a-f4cd-416f-8b43-4eafca0aa9e5.png">

## Guidelines for docs team

* Use tiles and tabs more carefully, sometimes a simple bullet list will work much better
* Do not disrupt readers flow with too many announcements, messages and notes
* Push links branching the readers flow to the end of any article.

**Comment by ptgott** [comment]
The Postgres docs are a really nice example of a docs site that resembles a book: https://www.postgresql.org/docs/current/

**Comment by ptgott** [comment]
The gnu awk guide is another docs site that's laid out like a book: https://www.gnu.org/software/gawk/manual/html_node/index.html#SEC_Contents

**Comment by ptgott** [comment]
## Checklist 

_Based on the original post above_

### Styling components to be less intrusive

- [ ] Make title read more like a classic title and remove banner style
- [ ] Make video banner less intrusive
- [x] Make tiles less intrusive, with less purple and read more like doc headers. **We no longer use tiles in menu pages within the documentation.**
- [ ] Make tabs more lightweight. Right now they are too heavy.
- [ ] Try another theme for code that focuses on actual code.
- [ ] Make `Notice` and `Admonition` components less disruptive to the readers' flow. They take away too much attention with very bright frames.

### Avoiding overuse of non-textual components in docs pages

I think the best way to address these will be to add linters to the docs engine. This is because docs authors (including myself) often reach for non-text components as a quick-and-dirty solution, so a linter will force us to slow down and think of a more text-focused way to convey the same information.
  
- [ ] Ensure that the docs are not using tiles and tabs too much. Sometimes a simple bullet list will work much better.
- [ ] Ensure that the docs do not disrupt the reader's flow with too many announcements, messages and notes
- [ ] Push links branching the reader's flow to the end of any article. (in how-to guides)

**Comment by ptgott** [comment]
Closing since moving to the Docusaurus site takes care of these requirements.
